__author__ = 'StefanFlorescu'


from collections import OrderedDict


income_pool = {
    1: dict(type1=True, type2=False, name="Temporary/Contract Work",
            data=OrderedDict([("proof", ["select", "ContractDeliveryMethod", "Email"]),
                              ("employment", ["select", "employment_likely_to_change", "No"]),
                              ("employment_start", ["date", "EmploymentStartDate", "01/01/2015"]),
                              ("job_title", ["input", "JobTitle", "QA Manager"]),
                              ("company", ["input", "EmployersCompanyName", "Draytus"]),
                              ("referee_name", ["input", "RefereeName", "MainIncome EmployerTest Name"]),
                              ("referee_address", ["postcode", "PostCode", "ba133bn"]),
                              ("referee_number", ["input", "RefereeBusinessLandlineNumber", "3256458498"]),
                              ("referee_email", ["input","RefereeEmailAddress", "testinginbox11@draytus.net"]),
                              ("months_remained", ["select", "months_remaining", 36])])),

    2: dict(type1=True, type2=False, name="Part Time Employed",
            data=OrderedDict([("proof", ["select", "ContractDeliveryMethod", "Email"]),
                              ("employment", ["select", "employment_likely_to_change", "No"]),
                              ("employment_start", ["date", "EmploymentStartDate", "01/01/2015"]),
                              ("job_title", ["input", "JobTitle", "QA Manager"]),
                              ("company", ["input", "EmployersCompanyName", "Draytus"]),
                              ("referee_name", ["input", "RefereeName", "MainIncome EmployerTest Name"]),
                              ("referee_address", ["postcode", "PostCode", "ba133bn"]),
                              ("referee_number", ["input", "RefereeBusinessLandlineNumber", "3256458498"]),
                              ("referee_email", ["input","RefereeEmailAddress", "testinginbox12@draytus.net"])])),

    3: dict(type1=True, type2=True, name="Full time Employed",
            data=OrderedDict([("proof", ["select", "ContractDeliveryMethod", "Email"]),
                              ("employment",["select", "employment_likely_to_change", "No"]),
                               ("employment_start", ["date", "EmploymentStartDate", "01/01/2015"]),
                              ("job_title", ["input", "JobTitle", "QA Manager"]),
                               ("company", ["input", "EmployersCompanyName", "Draytus"]),
                              ("referee_name", ["input", "RefereeName", "MainIncome EmployerTest Name"]),
                               ("referee_address", ["postcode", "PostCode", "ba133bn"]),
                              ("referee_number", ["input", "RefereeBusinessLandlineNumber", "3256458498"]),
                               ("referee_email", ["input","RefereeEmailAddress", "testinginbox13@draytus.net"])])),

    4: dict(type1=True, type2=False, name="Self-Employed",
            data= OrderedDict([("employed_time", ["select", "SelfEmployedPeriod", 3]),
                               ("have_accountant", ["select", "DoYouHaveAnAccountant", "Yes"]),
                               ("firm_name", ["input", "AccountancyFirmName", "Test Accountancy Firm"]),
                               ("referee_name", ["input", "RefereeName", "MainIncome Self-employment Accountancy"]),
                               ("referee_job", ["input", "RefereeJobTitle", "QA Manager"]),
                               ("referee_address", ["postcode", "PostCode", "ba133bn"]),
                               ("referee_number", ["input", "RefereeBusinessLandlineNumber", "78784654761"]),
                               ("referee_email", ["input", "RefereeEmailAddress", "testinginbox14@draytus.net"])])),

    5: dict(type1=True, type2=True, name = "Retired",
            data= OrderedDict([("have_proof", ["select", "DoYouHaveProofOfPension", "No"]),
                               ("pension_provider", ["input", "PensionProviderName", "UK National Pension Fund"]),
                               ("referee_name", ["input", "RefereeName", "MainIncome PensionTest"]),
                               ("referee_job", ["input", "RefereeJobTitle", "Social Assistant"]),
                               ("referee_address", ["postcode", "PostCode", "ba133bn"]),
                               ("referee_phone", ["input", "RefereeBusinessLandlineNumber", "879567831358"]),
                               ("referee_email", ["input", "RefereeEmailAddress", "testinginbox15@draytus.net"])])),

    6: dict(type1=True, type2=True, name="Student sponsorship/funding",
            data= OrderedDict([("delivery_method", ["select", "DocumentDeliveryMethod", "Email"]),
                               ("funding_organisation", ["input", "OrganisationName", "Oxford on Maine"]),
                               ("referee_name", ["input", "RefereeName", "MainIncome StudentTest"]),
                               ("referee_job", ["input", "RefereeJobTitle", "Student Affairs manager"]),
                               ("referee_address", ["postcode", "PostCode", "ba133bn"]),
                               ("referee_phone", ["input", "RefereeBusinessLandlineNumber", "879007831358"]),
                               ("referee_email", ["input", "RefereeEmailAddress", "testinginbox16@draytus.net"])])),

    7: dict(type1=True, type2=True, name="Private Income",
            data= OrderedDict([("who_toprovide", ["select", "ReferenceProvider", "Solicitor"]),
                               ("referee_business", ["input", "RefereeBusinessName", "Test Referee Business Name"]),
                               ("referee_name", ["input", "RefereeName", "MainIncome PrivateIncome"]),
                               ("referee_job", ["input", "RefereeJobTitle", "General Manager"]),
                               ("referee_address", ["postcode", "PostCode", "ba133bn"]),
                               ("referee_phone", ["input", "RefereeBusinessLandlineNumber", "899307831358"]),
                               ("referee_email", ["input", "RefereeEmailAddress", "testinginbox17@draytus.net"])])),

    7: dict(type1=True, type2=True, name="Foster Carer Income",
            data= OrderedDict([("who_toprovide", ["select", "ReferenceProvider", "Agency"]),
                               ("referee_business", ["input", "RefereeBusinessName", "Test Referee Business Name"]),
                               ("referee_name", ["input", "RefereeName", "MainIncome FosterIncome Test"]),
                               ("referee_job", ["input", "RefereeJobTitle", "Financial Manager"]),
                               ("referee_address", ["postcode", "PostCode", "ba133bn"]),
                               ("referee_phone", ["input", "RefereeBusinessLandlineNumber", "899307831358"]),
                               ("referee_email", ["input", "RefereeEmailAddress", "testinginbox17@draytus.net"])]))
}


applicants_pool = [
    {"name": ['RAYMOND ', 'SMITH ', '01/11/1945'], "address": ['3 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": False, "phone": True},
    {"name": ['ROGER ', 'HAYNE ', '01/11/1951'], "address": ['5 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": False, "phone": True},
    {"name": ['BEN ', 'SKUTANS ', '01/01/1976'], "address": ['6 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Co-habiting"], "ccj": False, "phone": False},
    {"name": ['John ', 'SKUTANS ', '01/06/1937'], "address": ['8 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Co-habiting"], "ccj": False, "phone": True},
    {"name": ['AMANDA ', 'RIDLINGTON', '01/11/1969'], "address": ['15 ', '16 ', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Ms", "Female", "British", "Married"], "ccj": False, "phone": False},
    {"name": ['ELIZABETH ', 'STOREY ', '01/04/1961'], "address": ['19 ', '22 ', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Ms", "Female", "British", "Married"], "ccj": False, "phone": False},
    {"name": ['KEVIN ', 'FRYER', '01/10/1963'], "address": ['20 ', '19 ', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": False, "phone": False},
    {"name": ['ROBERT', 'TAMDY', '01/06/1965'], "address": ['25 ', '26 ', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": False, "phone": False},
    {"name": ['RUTH ', 'GOODWIN', '01/12/1976'], "address": ['385 ', '386 ', '387 '], "bank": ['56-00-36', '44444443'],
     "details": ["Mr", "Male", "British", "Single"], "ccj": False, "phone": True},
    {"name": ['BRIAN ', 'CLARKSON ', '01/03/1940'], "address": ['313 ', '310 ', '316 '],
     "bank": ['56-00-36', '22222221'], "details": ["Mr", "Male", "British", "Married"], "ccj": False, "phone": False},
    {"name": ['BRIAN ', 'KERSHAW', '01/11/1968'], "address": ['518 ', '', ''], "bank": ['56-00-36', '22222221'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": False, "phone": True},
    {"name": ['JEFFREY ', 'LAWRENCE ', '01/11/1950'], "address": ['41 ', '39 ', ''], "bank": ['30-91-97', '77777771'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": False, "phone": False},
    {"name": ['JEFFREY ', 'WOODCOCK', '01/09/1961'], "address": ['404 ', '', ''], "bank": ['30-91-97', '77777771'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": False, "phone": False},
    {"name": ['KARL ', 'TOWNEND', '01/12/1971'], "address": ['474 ', '473 ', ''], "bank": ['07-01-16', '11111118'],
     "details": ["Mr", "Male", "British", "Civil Partnership"], "ccj": True, "phone": False},
    {"name": ['DAVID ', 'COLE', '01/08/1963'], "address": ['127 ', '', ''], "bank": ['56-00-36', '40308669'],
     "details": ["Mr", "Male", "British", "Co-habiting"], "ccj": False, "phone": False},
    {"name": ['DAVID ', 'PHILIPS', '01/07/1962'], "address": ['240 ', '239 ', ''], "bank": ['56-00-36', '40308669'],
     "details": ["Mr", "Male", "British", "Single"], "ccj": False, "phone": False},
    {"name": ['DAVID ', 'WISHART', '01/07/1956'], "address": ['245 ', '', ''], "bank": ['56-00-36', '40308669'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": False, "phone": True},
    {"name": ['DAVID ', 'SOUTHERN', '01/02/1970'], "address": ['417 ', '', ''], "bank": ['56-00-36', '40308669'],
     "details": ["Mr", "Male", "British", "Divorced"], "ccj": False, "phone": True},
    {"name": ['DAVID ', 'TURNER', '01/12/1957'], "address": ['442 ', '444 ', '443 '], "bank": ['56-00-36', '40308669'],
     "details": ["Mr", "Male", "British", "Separated"], "ccj": False, "phone": False},
    {"name": ['CERI ', 'TOULMAN', '01/12/1957'], "address": ['444 ', '445 ', '442 '], "bank": ['56-00-36', '40308669'],
     "details": ["Miss", "Female", "British", "Single"], "ccj": False, "phone": False},
    {"name": ['CHRIS ', 'JACKSON', '01/05/1948'], "address": ['456 ', '457 ', ''], "bank": ['56-00-36', '40308669'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": False, "phone": False},
    {"name": ['JACQUELINE', 'EDWARDS', '01/06/1951'], "address": ['461 ', '', ''], "bank": ['56-00-36', '40308669'],
     "details": ["Mrs", "Female", "British", "Widow(er)"], "ccj": False, "phone": False},
    {"name": ['D', 'GUEST', '01/12/1978'], "address": ['470 ', '471 ', ''], "bank": ['56-00-36', '40308669'],
     "details": ["Mr", "Male", "British", "Divorced"], "ccj": False, "phone": False},
    {"name": ['HATTIE ', 'GUEST', '01/06/1958'], "address": ['471 ', '', ''], "bank": ['56-00-36', '40308669'],
     "details": ["Mrs", "Female", "British", "Widow(er)"], "ccj": False, "phone": False},
    {"name": ['PAUL ', 'BIRKINSHAW ', '01/07/1958'], "address": ['485 ', '', ''], "bank": ['56-00-36', '40308669'],
     "details": ["Mr", "Male", "British", "Single"], "ccj": False, "phone": False},
    {"name": ['LESLIE ', 'DANIELS', '01/09/1964'], "address": ['486 ', '487 ', ''], "bank": ['56-00-36', '40308669'],
     "details": ["Miss", "Female", "British", "Civil Partnership"], "ccj": False, "phone": False},
    {"name": ['E ', 'SWANN ', '01/05/1975'], "address": ['489 ', '488 ', ''], "bank": ['56-00-36', '40308669'],
     "details": ["Mr", "Male", "British", "Divorced"], "ccj": False, "phone": False},
    {"name": ['Dian', 'Tamdy', '01/11/1965'], "address": ['27 ', '26 ', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Single"], "ccj": True, "phone": False},
    {"name": ['LINDSAY ', 'NAGY ', '01/07/1970'], "address": ['35 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Widow(er)"], "ccj": True, "phone": False},
    {"name": ['MOHAMMED ', 'BUTLER', '01/04/1956'], "address": ['42 ', '43 ', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": True, "phone": False},
    {"name": ['MUSHTAQ ', 'PICKARD', '01/01/1958'], "address": ['44 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Divorced"], "ccj": False, "phone": False},
    {"name": ['SHARON ', 'DRYDEN', '01/06/1973'], "address": ['54 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": True, "phone": False},
    {"name": ['CHRISTOPHER ', 'DRYDEN', '01/03/1974'], "address": ['55 ', '54 ', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Divorced"], "ccj": True, "phone": False},
    {"name": ['ELIZABETH ', 'Edwards', '01/04/1948'], "address": ['62 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Divorced"], "ccj": True, "phone": False},
    {"name": [' GEORGE', 'TYSOE', '01/01/1970'], "address": ['82 ', '81 ', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Divorced"], "ccj": True, "phone": False},
    {"name": ['ANITA ', 'WALTON', '01/04/1957'], "address": ['119 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Miss", "Female", "British", "Separated"], "ccj": True, "phone": False},
    {"name": ['ROY ', 'GEESON', '01/04/1950'], "address": ['137 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Civil Partnership"], "ccj": True, "phone": True},
    {"name": ['DAVID ', 'BROWN', '01/05/1964'], "address": ['220 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Divorced"], "ccj": True, "phone": False},
    {"name": ['FLORENCE ', 'ARCHER', '01/01/1936'], "address": ['218 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Miss", "Female", "British", "Widow(er)"], "ccj": True, "phone": False},
    {"name": ['PAM ', 'HEMINGWAY', '01/08/1955'], "address": ['263 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": True, "phone": False},
    {"name": ['MICK ', 'JOHNSON', '01/11/1941'], "address": ['267 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": True, "phone": False},
    {"name": ['PHILIP ', 'WILLIAMS', '01/12/1969'], "address": ['270 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Co-habiting"], "ccj": True, "phone": False},
    {"name": ['MICHAEL ', 'GARRAT', '01/09/1965'], "address": ['301 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Single"], "ccj": True, "phone": True},
    {"name": ['P', 'CLARKSON', '01/04/1969'], "address": ['309 ', '312 ', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": True, "phone": False},
    {"name": ['LYN ', 'SCOTT', '01/07/1970'], "address": ['316 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Ms", "Female", "British", "Divorced"], "ccj": True, "phone": False},
    {"name": ['MARK ', 'PARKES', '01/04/1961'], "address": ['318 ', '319 ', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": True, "phone": False},
    {"name": ['SANDRA ', 'CLARKE', '01/01/1952'], "address": ['464 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mrs", "Female", "British", "Co-habiting"], "ccj": True, "phone": True},
    {"name": ['Martin ', 'Wesley ', '01/11/1969'], "address": ['505 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": False, "phone": True},
    {"name": ['PHIL ', 'ALDRIDGE ', '01/03/1952'], "address": ['521 ', '520 ', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": False, "phone": True},
    {"name": ['D ', 'LINDLEY ', '01/08/1952'], "address": ['540 ', '', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mrs", "Female", "British", "Married"], "ccj": False, "phone": True},
    {"name": ['KEVIN ', 'HARDCASTLE ', '01/06/1960'], "address": ['425 ', '424 ', ''], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": False, "phone": False},
    {"name": ["JOHN ", "WALES", "01/04/1959"], "address": ["THE OLD VICARAGE", "12 ", "QUARRY HOUSE"],
     "bank": ['56-00-36', '57607230'], "details": ["Mr", "Male", "British", "Married"], "ccj": True, "phone": False},
    {"name": ["ELIZABETH ", "COLLIER", "01/04/1959"], "address": ["THE OAKS", "563 ", ""],
     "bank": ['56-00-36', '57607230'], "details": ["Mrs", "Female", "British", "Married"], "ccj": False,
     "phone": False},
    {"name": ["AMANDA", "SHIRT", "01/09/1967"], "address": ["THE NEST", "", ""], "bank": ['56-00-36', '57607230'],
     "details": ["Mrs", "Female", "British", "Married"], "ccj": True, "phone": False},
    {"name": ["KEN", "LINDEN", "01/02/1965"], "address": ["THE GARDNERS COTTAGE RUSHWOOD", "", ""],
     "bank": ['56-00-36', '57607230'], "details": ["Mr", "Male", "British", "Married"], "ccj": False, "phone": False},
    {"name": ["CAROL", "MAERRITT", "01/05/1959"], "address": ["SHIRE BARN", "High Trees", "Moorfields"],
     "bank": ['56-00-36', '57607230'], "details": ["Mrs", "Female", "British", "Married"], "ccj": False,
     "phone": False},
    {"name": ["ROY", "JACQUES", "01/09/1942"], "address": ["THE FIVE KILNS", "", ""], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": False, "phone": True},
    {"name": ["ALAN", "GLOVER ", "01/09/1969"], "address": ["TENBY", "389 ", "390 "], "bank": ['56-00-36', '57607230'],
     "details": ["Mr", "Male", "British", "Married"], "ccj": False, "phone": False},
    {"name": ["SUSAN", "TAYLOR ", "01/01/1943"], "address": ["PICKENHAM HOUSE", "Glenhurst Lodge", ""],
     "bank": ['56-00-36', '57607230'], "details": ["Mrs", "Female", "British", "Married"], "ccj": False,
     "phone": False},
    {"name": ["JENNIE", "FLEETWOOD ", "/07/1950"], "address": ["LLWYN ONN", "", ""], "bank": ['56-00-36', '57607230'],
     "details": ["Mrs", "Female", "British", "Married"], "ccj": False, "phone": True},
    {"name": ["SUE ", "BROWN ", "01/03/1950"], "address": ["LITTLECOTE", "448", ""], "bank": ['56-00-36', '57607230'],
     "details": ["Mrs", "Female", "British", "Married"], "ccj": False, "phone": True},
    {"name": ["SUSAN", "TAYLOR ", "01/01/1943"], "address": ["GLENHURST LODGE ", "Pickenham House", ""],
     "bank": ['56-00-36', '57607230'], "details": ["Mrs", "Female", "British", "Married"], "ccj": False, "phone": True},
    {"name": ["STEPHEN", "STOMER", "01/01/1960"], "address": ["FLATTS", "Tree Tops", ""],
     "bank": ['56-00-36', '57607230'], "details": ["Mr", "Male", "British", "Married"], "ccj": False, "phone": False}
]



user_pool = dict(

    production=dict(
        url="letrisks-acumen.com",
        LetRisks=dict(manager=["Letrisks", "lr_manager@letrisks-acumen.com", "lr_manager", "None"],
                      area_manager=["QA Area Manager", "testingsitesqa@yandex.com", "123456", "None"],
                      branch_manager=["QA Branch Manager", "testingsitesqa@outlook.com", "123456", "None"],
                      agent=["QA test", "testinginbox@yahoo.com", "123456", "None"],
                      operator=["Draytus Operator", "testingsitesqa@hotmail.com", "123456", "None"])),

    sandbox=dict(
        url="http://sandbox.letrisks-acumen.com",
        Letrisks=dict(manager=["Letrisks", "lr_manager@letrisks-acumen.com", "4cEfruzacr", "LetRisks"],
                      area_manager=[],
                      branch_manager=[],
                      agent=["QA Test", "testinginbox@yahoo.com", "123456", "LetRisks"],
                      operator=[]),
        Draytus=dict(manager=["QA Draytus", "draytus_manager@letrisks-acumen.com", "123456"],
                     area_manager=["QA Area Manager", "testingsitesqa@yandex.com", "123456"],
                     branch_manager=["QA Branch Manager", "testingsitesqa@outlook.com", "123456"],
                     agent=["Draytus Test", "testinginbox@gmail.com", "123456"],
                     operator=["QA Operator", "testingsitesqa@hotmail.com", "123456"]),
        API_Customer=dict(manager=[], area_manager=[],
                          branch_manager=[],
                          agent=["QA API Test", "testinginbox@yahoo.com", "123456"],
                          operator=[])),

    preprod= dict(
        url="http://homespun.pre-prod.net",
        Draytus=dict(manager=["QA Draytus", "draytus_manager@letrisks-acumen.com", "123456", "et-1"],
                 area_manager=["QA Area Manager", "testingsitesqa@yandex.com", "123456", "et-1"],
                 branch_manager=["QA Branch Manager", "testingsitesqa@outlook.com", "123456", "et-1"],
                 agent=["Draytus Test", "testinginbox@gmail.com", "123456", "et-1"],
                 operator=["QA Operator", "testingsitesqa@hotmail.com", "123456", "et-1"])),

    testing = dict(
        url="http://homespuntesting.lan",
        Draytus=dict(manager=["QA Draytus", "lr_manager@letrisks-acumen.com", "lr_manager", "et-1"],
                 area_manager=["QA Area Manager", "testingsitesqa@yandex.com", "123456", "et-1"],
                 branch_manager=["QA Branch Manager", "testingsitesqa@outlook.com", "123456", "et-1"],
                 agent=["Draytus Test", "testinginbox@yahoo.com", "123456", "et-1"],
                 operator=["QA Operator", "testingsitesqa@hotmail.com", "123456", "et-1"]))
)